// apps/playground-svelte/src/App.svelte
<script lang="ts">
  import { EmailAutomationWidget } from "@eaw/svelte";
</script>

<div class="page">
  <h1>Monorepo Playground — Svelte</h1>
  <div class="card">
    <EmailAutomationWidget baseURL="http://localhost:8000/api" token="test_token_123" mode="mailbox" />
  </div>
</div>

<style>
  .page {
    padding: 40px;
    background-color: #f3f4f6;
    min-height: 100vh;
  }
  .card {
    max-width: 800px;
    margin: 0 auto;
    background-color: #fff;
    border-radius: 8px;
  }
</style>

// apps/playground-react/src/App.tsx
import { EmailAutomationWidget } from "../../../packages/react/src/index";

function App() {
  return (
    <div
      style={{
        padding: "40px",
        backgroundColor: "#f3f4f6",
        minHeight: "100vh",
      }}
    >
      <h1>Monorepo Playground</h1>
      <div
        style={{
          maxWidth: "800px",
          margin: "0 auto",
          backgroundColor: "#fff",
          borderRadius: "8px",
        }}
      >
        <EmailAutomationWidget
          baseURL="http://localhost:8000/api"
          token="test_token_123"
          mode="mailbox"
        />
      </div>
    </div>
  );
}

export default App;
